/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  // Some arbitrary-value utilities in `LoginPage.jsx` weren't consistently
  // generated by Tailwind in dev. Safelist them so login styling always lands.
  safelist: [
    // Gradient background
    'bg-gradient-to-br',
    'from-[#f4f7f2]',
    'via-[#f8faf7]',
    'to-[#e9f0e4]',
    'from-[#244015]',
    'to-[#385f21]',

    // Floating blobs / panels
    'bg-[#6b8b52]/20',
    'bg-[#2d5016]/15',
    'border-[#d8e3cf]',
    'shadow-[0_16px_50px_rgba(28,53,16,0.16)]',
    'bg-[#d7e8ca]',
    'bg-[#2d5016]',

    // Text + borders
    'text-[#1f3220]',
    'text-[#607163]',
    'text-[#2d3f2f]',
    'text-[#2f5a1f]',
    'border-[#cfdbca]',
    'focus:border-[#2f5a1f]',
    'focus:ring-[#7ea06c]/25',

    // Button hover
    'hover:bg-[#eef4e9]',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
